backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: content/uploads
public_folder: ../uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/IndexPage.md"
        label: "Startseite"
        name: "IndexPage"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Inhalt, name: body, widget: markdown }