backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: content/uploads
public_folder: ../uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
    
      - file: "content/pages/Startseite.md"
        label: "Startseite"
        name: "Startseite"
        fields:
          - { label: Bild, name: image, widget: image }
          - { label: Inhalt, name: body, widget: markdown }
          - { label: Text 1, name: text1, widget: string }
          - { label: Video, name: video, widget: string }
          - { label: Text 2, name: text2, widget: string }
          - { label: Foto 1, name: photo1, widget: image }
          - { label: Text 3, name: text3, widget: string }
          - { label: Foto 2, name: photo2, widget: image }

      - file: "content/pages/Verein.md"
        label: "Mitgestalten"
        name: "Verein"
        fields:
          - { label: Inhalt, name: body, widget: markdown }
