backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: content/uploads
public_folder: ../uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/Startseite.md"
        label: "Startseite"
        name: "Startseite"
        fields:
          - { label: Bild, name: image, widget: image }
          - { label: Bildtitel, name: imageTitle, widget: string }
          - { label: Inhalt, name: body, widget: markdown }
      - file: "content/pages/Verein.md"
        label: "Oben Unten e.V."
        name: "Verein"
        fields:
          - { label: Inhalt, name: body, widget: markdown }